name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    
    - name: Build app
      run: |
        xcodebuild -project "AI resource tracker.xcodeproj" \
                   -scheme "AI resource tracker" \
                   -configuration Release \
                   -derivedDataPath ./build \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO
    
    - name: Create zip
      run: |
        cd build/Build/Products/Release
        ditto -c -k --keepParent "AI resource tracker.app" "AI-Resource-Tracker.app.zip"
        mv "AI-Resource-Tracker.app.zip" $GITHUB_WORKSPACE/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: AI-Resource-Tracker.app.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
